[UI-07] Make form adaptive
miska924/TimeSeriesForecast pull request #26
Opened 2021-05-23 14:37 UTC by beastSL

Signed-off-by: Sergei Loptev <seloptev@gmail.com>

2021-05-23 17:50 UTC, miska924 submitted a review, later dismissed

2021-05-23 17:55 UTC, miska924 commented
![image](https://user-images.githubusercontent.com/37046508/119271187-27990780-bc09-11eb-9ac2-47c6d5afc03c.png)

при запуске у линрега нет экзогенок

2021-05-24 20:36 UTC, DanglSan requested changes

2021-05-24 20:36 UTC, DanglSan commented on source/client/config.py
>  import enum
Надо бы разделить импорты на сторонние библиотеки и модули проекта

2021-05-26 12:45 UTC, DanglSan approved these changes

2021-05-26 12:51 UTC, DanglSan approved these changes

2021-05-26 12:51 UTC, merged